[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "happyflow"
version = "0.0.4"
authors = [
  { name="Andre Hora", email="andrehoraa@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/andrehora/happyflow"
"Bug Tracker" = "https://github.com/andrehora/happyflow/issues"