name: install-dev

on: [workflow_dispatch]
# on:
#   workflow_run:
#     workflows: ["tests"]
#     branches: [main]
#     types: 
#       - completed

jobs:

  install:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install SpotFlow - dev
        run: sh scripts/install-dev.sh
      - name: Run SpotFlow - dev
        run: sh scripts/run.sh